matrix:
    homeserver: https://matrix.raspad.space
    username: meshrelayer
    password: aczBRERO3LcOMff
    device_id: MESHBOT

room:
    target_room: "!mSmjqRsxficDk2Xxw6:matrix.raspad.space"
    allowed_user: "@admin:matrix.raspad.space"

        



